export type BibleBook = {
  id: string;
  name: string;
  testament: "OT" | "NT";
};

export const BIBLE_BOOKS: BibleBook[] = [
  // Old Testament
  { id: "gen", name: "Genesis", testament: "OT" },
  { id: "exo", name: "Exodus", testament: "OT" },
  { id: "lev", name: "Leviticus", testament: "OT" },
  { id: "num", name: "Numbers", testament: "OT" },
  { id: "deu", name: "Deuteronomy", testament: "OT" },
  { id: "jos", name: "Joshua", testament: "OT" },
  { id: "jdg", name: "Judges", testament: "OT" },
  { id: "rut", name: "Ruth", testament: "OT" },
  { id: "1sa", name: "1 Samuel", testament: "OT" },
  { id: "2sa", name: "2 Samuel", testament: "OT" },
  { id: "1ki", name: "1 Kings", testament: "OT" },
  { id: "2ki", name: "2 Kings", testament: "OT" },
  { id: "1ch", name: "1 Chronicles", testament: "OT" },
  { id: "2ch", name: "2 Chronicles", testament: "OT" },
  { id: "ezr", name: "Ezra", testament: "OT" },
  { id: "neh", name: "Nehemiah", testament: "OT" },
  { id: "est", name: "Esther", testament: "OT" },
  { id: "job", name: "Job", testament: "OT" },
  { id: "psa", name: "Psalms", testament: "OT" },
  { id: "pro", name: "Proverbs", testament: "OT" },
  { id: "ecc", name: "Ecclesiastes", testament: "OT" },
  { id: "sng", name: "Song of Solomon", testament: "OT" },
  { id: "isa", name: "Isaiah", testament: "OT" },
  { id: "jer", name: "Jeremiah", testament: "OT" },
  { id: "lam", name: "Lamentations", testament: "OT" },
  { id: "ezk", name: "Ezekiel", testament: "OT" },
  { id: "dan", name: "Daniel", testament: "OT" },
  { id: "hos", name: "Hosea", testament: "OT" },
  { id: "jol", name: "Joel", testament: "OT" },
  { id: "amo", name: "Amos", testament: "OT" },
  { id: "oba", name: "Obadiah", testament: "OT" },
  { id: "jon", name: "Jonah", testament: "OT" },
  { id: "mic", name: "Micah", testament: "OT" },
  { id: "nam", name: "Nahum", testament: "OT" },
  { id: "hab", name: "Habakkuk", testament: "OT" },
  { id: "zep", name: "Zephaniah", testament: "OT" },
  { id: "hag", name: "Haggai", testament: "OT" },
  { id: "zec", name: "Zechariah", testament: "OT" },
  { id: "mal", name: "Malachi", testament: "OT" },

  // New Testament
  { id: "mat", name: "Matthew", testament: "NT" },
  { id: "mrk", name: "Mark", testament: "NT" },
  { id: "luk", name: "Luke", testament: "NT" },
  { id: "jhn", name: "John", testament: "NT" },
  { id: "act", name: "Acts", testament: "NT" },
  { id: "rom", name: "Romans", testament: "NT" },
  { id: "1co", name: "1 Corinthians", testament: "NT" },
  { id: "2co", name: "2 Corinthians", testament: "NT" },
  { id: "gal", name: "Galatians", testament: "NT" },
  { id: "eph", name: "Ephesians", testament: "NT" },
  { id: "php", name: "Philippians", testament: "NT" },
  { id: "col", name: "Colossians", testament: "NT" },
  { id: "1th", name: "1 Thessalonians", testament: "NT" },
  { id: "2th", name: "2 Thessalonians", testament: "NT" },
  { id: "1ti", name: "1 Timothy", testament: "NT" },
  { id: "2ti", name: "2 Timothy", testament: "NT" },
  { id: "tit", name: "Titus", testament: "NT" },
  { id: "phm", name: "Philemon", testament: "NT" },
  { id: "heb", name: "Hebrews", testament: "NT" },
  { id: "jas", name: "James", testament: "NT" },
  { id: "1pe", name: "1 Peter", testament: "NT" },
  { id: "2pe", name: "2 Peter", testament: "NT" },
  { id: "1jn", name: "1 John", testament: "NT" },
  { id: "2jn", name: "2 John", testament: "NT" },
  { id: "3jn", name: "3 John", testament: "NT" },
  { id: "jud", name: "Jude", testament: "NT" },
  { id: "rev", name: "Revelation", testament: "NT" },
];
